;**************************
; Universidad del Valle de Guatemala
; Programación de Microcrontroladores
; Proyecto: Laboratorio Contador
; Archivo: Contador_Laboratoio_1_Progra_de_Micro.asm
; Hardware: ATMEGA328p
; Created: 30/01/2024 18:11:46
; Author : RUDY GREGORIO
;**************************
;**************************

.include "M328PDEF.inc" ; p
.cseg ; 
.org 0x00 ; 
;**************************
; STACK INICIAL
;**************************
LDI R16, LOW(RAMEND)
OUT SPL, R16 
LDI R17, HIGH(RAMEND)
OUT SPH, R17
;**************************
; Configuración
;**************************
Setup:
	LDI R16, (1 << CLKPCE)
	STS CLKPR, R16 ;HABILITAMOS EL PRESCALER

	LDI R16, 0b0000_0011 ;METEMOS ESE VALOR EN BINARIO EN EL REGISTRO R16
	STS CLKPR, R16 ;DEFINIMOS UNA FRECUENCIA DE 2MHz

	LDI R16, 0b0001_1111 ; CONFIGURAMOS LOS PULLUPS 
	OUT PORTC, R16	; HABILITAMOS EL PULLUPS
	LDI R18, 0b0000_0000 ;METEMOS ESE VALOR EN BINARIO EN EL REGISTRO R18
	OUT DDRC, R18 ; DEFINIMOS COMO ENTRADAS LOS PUERTOS C

	LDI R16, 0b1111_1111 ;METEMOS ESE VALOR EN BINARIO EN EL REGISTRO R16
	OUT DDRD, R16 ;DEFINIMOS CÓMO SALIDA LOS PUERTOS D
	LDI R16, 0b0001_1111 ;METEMOS ESE VALOR EN BINARIO EN EL	 REGISTRO R16
	OUT DDRB, R16 ;DEFINIMOS CÓMO SALIDAS LOS PRIMEROS 5 PINS B Y EL RESTO SON ENTRADAS


Loop:
	SBRC PORTC, 0
	CALL INC1

	SBRC PORTC, 1
	CALL DEC1

	SBRC PORTC, 2
	CALL INC2

	SBRC PORTC, 3
	CALL DEC2

	SBRC PORTC, 4
	CALL SUMAR

	
	SWAP R21
	
	LDI R16, 0B0000_1111
	AND R16, R20
	OR R16, R21
	OUT PORTD, R16
	
	
	RJMP LOOP


;**************************
; Subrutinas
;**************************
;ESPERAMOS UN BREVE TIEMPO 
DELAY:
	LDI R16, 100; METEMOS EL VALOR DECIMAL DE "100" EN EL REGISTRO 100
DELAY LOOP:
	DEC R16
	BRNE DELAY ; SI NO ES IGUAL A CERO, RECGRESA EL DELAY
	RET
INC1:
	CALL DELAY
	SBIS PINC, PC0 ; SI EL BIT "0" DEL PINC ESTÁ ENCENDIDO SALTA DE LÍNEA.
	RJMP INC1 ; REGRESO A LA FUNCIÓN DB
	INC R20 ; INCREMENTO EL VALOR DE R17
	SBRC R20, 4 ; SI EL BIT "4" DEL REGISTRO 17 ESTÁ APAGADO SALTA A LA LÍNEA DE JUMP
	CLR R20 ;SE LIMPIA EL VALOR DE R17
	//OUT PIND, R20	
	RJMP Loop; VOLVEMOS AL LOOP

DEC1:
	CALL DELAY
	SBIS PINC, PC1 ; SI EL BIT "1" DEL PINC ESTÁ ENCENDIDO SALTA DE LÍNEA.
	RJMP DEC1 ; REGRESO A LA FUNCIÓN DB
	DEC R20 ; DECREMENTO EL VALOR DE R17
	SBRC R20, 4 ; SI EL BIT "4" DEL REGISTRO 20 ESTÁ APAGADO SALTA A LA LÍNEA DE JUMP
	LDI R20, 0B0000_1111
	RJMP Loop; VOLVEMOS AL LOOP



INC2:
	CALL DELAY
	SBIS PINC, PC2 ; SI EL BIT "0" DEL PINC ESTÁ ENCENDIDO SALTA DE LÍNEA.
	RJMP INC2 ; REGRESO A LA FUNCIÓN DB
	INC R21 ; INCREMENTO EL VALOR DE R17
	SBRC R21, 4 ; SI EL BIT "4" DEL REGISTRO 17 ESTÁ APAGADO SALTA A LA LÍNEA DE JUMP
	CLR R21 ;SE LIMPIA EL VALOR DE R17
	//OUT PIND, R20	
	RJMP Loop; VOLVEMOS AL LOOP

DEC2:
	CALL DELAY
	SBIS PINC, PC3 ; SI EL BIT "1" DEL PINC ESTÁ ENCENDIDO SALTA DE LÍNEA.
	RJMP DEC2 ; REGRESO A LA FUNCIÓN DB
	DEC R21 ; DECREMENTO EL VALOR DE R17
	SBRC R21, 4 ; SI EL BIT "4" DEL REGISTRO 17 ESTÁ APAGADO SALTA A LA LÍNEA DE JUMP
	LDI R21, 0B0000_1111
	RJMP Loop; VOLVEMOS AL LOOP


SUMAR:
	CALL DELAY
	MOV R25, R20
	ADD R25, R21
	OUT PORTD, R25
	RJMP LOOP